### ISSUE TITLE
Program not starting

### ISSUE THREAD

**Issue by TheGiolly** [zekroTJA/meautosd#1]
Hi, I have an issue with your program.
I downloaded both CSCore.dll and meautosd.exe (1.4.3.0) and they are in the same folder (Desktop).
When I try to open the application nothing happens (also tried running as Administrator).
Running Windows 10 x64 with Adobe Media Encoder CC 2017

**Comment by zekroTJA** [comment]
Thanks for the report.

Now, also for official, I removed the system diagnostics in version 1.4.4.0 to solve that issue. 

[Closed]

**Comment by abdellahaski** [comment]
This still not working on AME 2020
